version: "3.2"
services:
  bps_haproxy:
    image: $REGISTRY:5000/tools/haproxy:1.8-alpine
    networks:
      - nw_dmz
    ports:
      - 9003:9000
    volumes:
      - ${WORK_DIR}/openapi/config/haproxy/rsyslog_haproxy.conf:/etc/rsyslog.d/haproxy.conf
      - ${WORK_DIR}/openapi/config/haproxy/logrotate_haproxy:/etc/logrotate.d/haproxy
      - ${WORK_DIR}/openapi/config/haproxy/crontab_logrotate:/etc/cron.hourly/logrotate
      - ${WORK_DIR}/openapi/config/haproxy/dmz-out-haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ${LOG_DIR}/dmz-out-haproxy:/usr/src/logs
    env_file:
      - ${WORK_DIR}/swarm.env
    deploy:
      mode: global
      placement:
        constraints: [node.labels.dtb == true]
  postgresql:
    image: $REGISTRY:5000/tools/postgres:bitnami-11
    networks:
      - nw_dmz
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    # command: postgres -c max_connections=300 -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgres/data/logs
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    volumes:
      - ${DATA_DIR}/postgres:/bitnami/postgresql
      - ${WORK_DIR}/openapi/config/postgresql/:/bitnami/postgresql/conf/
      - ${LOG_DIR}/postgres:/bitnami/logs
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.labels.postgres == true]
  rabbitmq-seed:
    image: $REGISTRY:5000/tools/rabbitmq-cluster:latest
    networks:
      - nw_dmz
    hostname: rabbitmq-seed
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq
      - RABBITMQ_MANAGEMENT_PLUGIN=1
      - RABBITMQ_CLUSTER_SEED=rabbitmq-seed
    volumes:
      # - ${DATA_DIR}/rabbitmq-seed/data/:/var/lib/rabbitmq/
      - ${LOG_DIR}/rabbitmq-seed/:/var/log/rabbitmq/
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.dtb == true]
  rabbitmq:
    image: $REGISTRY:5000/tools/rabbitmq-cluster:latest
    networks:
      - nw_dmz
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq
      - RABBITMQ_MANAGEMENT_PLUGIN=1
      - RABBITMQ_CLUSTER_SEED=rabbitmq-seed
    volumes:
      # - ${DATA_DIR}/rabbitmq/data/:/var/lib/rabbitmq/
      - ${LOG_DIR}/rabbitmq/:/var/log/rabbitmq
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints: [node.labels.dtb == true]
  cache-redis-master:
    image: $REGISTRY:5000/tools/redis
    networks:
      - nw_dmz    
    volumes:
      - ${DATA_DIR}/redis/data:/data
      - ${WORK_DIR}/openapi/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${LOG_DIR}/redis-master/:/logs
    env_file:
      - ${WORK_DIR}/swarm.env
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.labels.dtb == true]
  cache-redis-slave:
    image: $REGISTRY:5000/tools/redis-slave
    networks:
      - nw_dmz
    volumes:
      - ${DATA_DIR}/redis/data:/data
      - ${LOG_DIR}/redis-slave/:/logs
    env_file:
      - ${WORK_DIR}/swarm.env
    ports:
      - "6380:6379"
    deploy:
      mode: global
      placement:
        constraints: [node.labels.dtb == true]
  #redis socket
  cache-redis-socket:
    image: $REGISTRY:5000/tools/redis
    networks:
      - nw_dmz
    volumes:
      - ${WORK_DIR}/openapi/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${LOG_DIR}/redis-socket/:/logs
    env_file:
      - ${WORK_DIR}/swarm.env
    ports:
      - target: 6379
        published: 6381
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.labels.dtb == true]
  cache-redis-market:
    image: $REGISTRY:5000/tools/redis
    networks:
      - nw_dmz
    volumes:
      - ${WORK_DIR}/openapi/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${LOG_DIR}/redis-market/:/logs
    env_file:
      - ${WORK_DIR}/swarm.env
    ports:
      - target: 6379
        published: 6382
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.labels.dtb == true]
  cache-redis-pubsub:
    image: $REGISTRY:5000/tools/redis
    networks:
      - nw_dmz  
    volumes:
      - ${WORK_DIR}/openapi/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${LOG_DIR}/redis-pubsub/:/logs
    env_file:
      - ${WORK_DIR}/swarm.env
    ports:
      - target: 6379
        published: 6383
        protocol: tcp
        mode: host      
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.labels.dtb == true]
networks:
  nw_dmz:
    external: true