HTTP/1.1 429 Too many request
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<!DOCTYPE html>
<html>
   <head>
     <style>
	   body {background-color: white;}
     </style>
   </head>
<body>

<h1>429 Too many request</h1>
<p>Too many requests to the system, please try again in a few minutes</p>

</body>
</html>