INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597380397215, 1597380397215, 13, 'Ôtô & linh kiện phụ tùng', 'Automobiles & Parts', 'CMC,CSM,CTF,DRC,FTI,GGG,HAX,HHS,HTL,SRC,SVC,TCH,TMT,VKC,VMA');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597380532033, 1597380532033, 17, 'Viễn thông', 'Telecommunications', 'ABC,FOX,MFS,PAI,PIA,PTP,TTN,VGI');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597379679268, 1598595083744, 4, 'Dầu khí', 'Oil & Gas', 'BSR,OIL,PEQ,PLX,POS,PTV,PVB,PVC,PVD,PVE,PVS');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597379870620, 1597379870620, 8, 'Đồ dùng cá nhân & đồ gia dụng', 'Personal & Household Goods', 'A32,AAT,ADS,AG1,AGB,AQN,ASA,ATD,BBT,BDG,BEL,BKG,BMG,BVN,CET,CLC,DCG,DCS,DM7,DQC,DTN,EVE,FBA,FTM,G20,GDT,GIL,GLT,GMC,GTD,GTK,HCB,HDM,HFS,HJC,HKC,HLG,HLT,HNE,HNI,HSM,HTG,HUG,KMR,KSD,LGM,LIX,M10,MEG,MGG,MNB,MPT,MSH,NDT,NET,NHT,NJC,NST,NTT,PNJ,PPH,PTG,RAL,SGI,SHE,SPB,SSF,STK,SVD,TAG,TCM,TDT,TET,TLG,TLI,TMW,TNG,TTG,TVT,VDM,VDN,VGG,VGT,VTI,VTJ,X20,X26,XHC,XPH');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597379718274, 1597379718274, 5, 'Dịch vụ bán lẻ', 'Retail', 'ABS,AFX,AGX,BSC,BTT,CEN,CGL,CMV,COM,CPH,DGW,DKC,FHN,FRT,GEM,HFX,HTM,HTT,IED,KGM,MWG,PET,PIT,PNG,PSD,PSH,SAD,SBV,T12,TBH,TBH,TH1,THS,TOP,TTH,TV6,VPG,VT1');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597379788176, 1597379788176, 6, 'Dịch vụ tài chính', 'Financial Services', 'AAS,AGR,APG,APS,ART,BCG,BMS,BSI,BVS,CSI,CTS,DSC,E1VFVN30,EVF,EVS,FIT,FTS,FUCTVGF2,FUCVREIT,FUEMAV30,FUESSV30,FUESSV50,FUESSVFL,FUEVFVND,FUEVN100,HAC,HBS,HCM,HFT,IBC,IVS,MBS,OGC,ORS,PHS,PSI,SBS,SHS,SSI,TCI,TVB,TVC,TVS,VCI,VDS,VFS,VIG,VIX,VND,WSS');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597380332684, 1597380332684, 11, 'Hóa chất', 'Chemicals', 'AAA,APP,BFC,BRC,BRR,BT1,CPC,CSV,DAG,DCI,DCM,DDV,DGC,DHB,DOC,DPD,DPM,DPR,DRG,DRI,DTT,GER,GVR,HAI,HCD,HII,HNP,HPH,HRC,HSI,HVT,IRC,LAS,LNC,LTG,NFC,NHH,NNG,NSG,PCE,PCN,PGN,PHR,PLC,PLP,PMB,PPV,PSE,PSW,PVO,QBS,RBC,RDP,RTB,SBR,SEP,SFG,SIV,SPC,TNC,TPC,TRC,TSC,VAF,VET,VFG,VKP,VNP,VNY,VPS,VTQ,VXP');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597379598925, 1597379598925, 2, 'Bất động sản', 'Real Estate', 'AAV,AGG,AMD,API,BCM,BII,BVL,C21,CCI,CCL,CEO,CLG,CLX,CRE,CSC,D11,D2D,DCH,DIG,DLR,DO3,DRH,DTA,DXG,DXS,EFI,EIN,FDC,FHH,FID,FIR,FLC,HAR,HD2,HD6,HD8,HDC,HDG,HIZ,HLD,HPI,HPX,HQC,HRB,HTN,HU6,IDC,IDJ,IDV,IJC,ITA,ITC,KAC,KBC,KDH,KHA,KOS,LBC,LDG,LEC,LGL,LHG,MH3,NBB,NDN,NLG,NRC,NTB,NTC,NTL,NVL,NVT,PDR,PFL,PIV,PLA,PPI,PTL,PTN,PV2,PVL,PVR,PWA,PXA,PXC,PXL,QCG,RCL,SCR,SGR,SID,SIP,SJS,SSE,SSH,STL,SZB,SZC,SZL,TBR,TDH,TEG,THD,TID,TIG,TIP,TIX,TLD,TLP,TN1,V11,VC3,VCR,VGV,VHD,VHM,VIC,VNI,VPH,VPI,VRC,VRE,VRG,XDH');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597379833224, 1597379833224, 7, 'Dịch vụ tiện ích', 'Utilities', 'ASP,AVC,BDW,BGW,BHA,BLW,BMF,BNW,BPT,BPW,BSA,BTP,BTW,BWA,BWE,BWS,CGC,CHP,CHS,CLW,CMW,CNG,CTW,CVH,DBW,DDG,DNA,DNC,DNH,DNN,DNW,DRL,DTE,DTV,DWC,DWS,EAD,EBA,GAS,GCB,GDW,GE2,GEG,GHC,GLW,GSM,HBW,HDW,HFC,HGW,HJS,HNA,HND,HPD,HPW,HTC,HTE,HTW,HWS,ISH,KHP,KHW,KTW,KWA,LAW,LCW,LDW,LKW,LMH,LWS,MTG,NAW,NBP,NBT,NBW,NCP,ND2,NDW,NLS,NNB,NNT,NQB,NQN,NQT,NS2,NS3,NSL,NT2,NTH,NTW,NVP,PBK,PCG,PDT,PEG,PGC,PGD,PGS,PGV,PIC,PJS,PMG,PMW,PND,POB,POV,POW,PPC,PPY,PTH,PVG,PWS,QNW,QPH,QTP,S4A,SBA,SBH,SEB,SFC,SHP,SJD,SP2,STW,SVH,TAW,TBC,TDB,TDG,TDM,TDW,THN,THW,TMC,TMP,TNW,TOW,TQW,TTE,TVW,UPC,VAV,VCW,VIW,VLW,VMG,VPD,VPW,VSH,VWS,XMP');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597379484307, 1599550331407, 1, 'Bảo hiểm', 'Insurance', 'ABI,AIC,BIC,BLI,BMI,BVH,MIG,PGI,PRE,PTI,PVI,VNR');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597380466328, 1597380466328, 15, 'Tài nguyên', 'Basic Resources', 'ACM,AFC,ALV,AMC,ATG,BAM,BCB,BKC,BMC,BMJ,BVG,CAP,CBI,CK8,CLM,CMI,CST,DFC,DHC,DHM,DLG,DNS,DNY,DPS,DTL,FRC,FRM,GLC,GTA,GVT,HAP,HGM,HHP,HLA,HLC,HMC,HMG,HPG,HPM,HSG,HSV,HTS,HUX,ITQ,KCB,KHB,KHD,KKC,KLM,KMT,KNA,KSA,KSB,KSH,KSQ,KSS,KSV,KTL,KVC,LCM,LMC,MC3,MDC,MDF,MEL,MGC,MHL,MIC,MIM,MMC,MSR,MTA,MTM,MVB,MXC,NBC,NHV,NKG,NSH,PAS,PIS,POM,RRC,SCA,SHA,SHI,SMC,SPI,SQC,SSM,SVT,TC6,TCP,TDN,TDS,THT,TIS,TKG,TKU,TLH,TMB,TMG,TNA,TNB,TNI,TNS,TNT,TQN,TTF,TTS,TVD,TVN,VBG,VCA,VDB,VDT,VGL,VGS,VID,VIF,VIM,VIS,YBM');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597380365384, 1598595101554, 12, 'Ngân hàng', 'Banks', 'ABB,ACB,BAB,BID,BVB,CTG,EIB,HDB,KLB,LPB,MBB,MSB,NAB,NVB,OCB,PGB,SGB,SHB,SSB,STB,TCB,TPB,VAB,VBB,VCB,VIB,VPB');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597380503186, 1597380503186, 16, 'Thực phẩm & Đồ uống', 'Food & Beverage', 'AAM,ABT,ACL,AGF,AGM,ANT,ANV,APF,APT,ASM,ATA,ATP,AUM,AVF,BBC,BBM,BCF,BHG,BHK,BHN,BHP,BKH,BLF,BLT,BMV,BNA,BQB,BSD,BSH,BSL,BSP,BSQ,BTB,C22,CAD,CAF,CAN,CAT,CBC,CBS,CCA,CFC,CFV,CMF,CMN,CMX,CPA,CTP,DAT,DBC,DMN,DTF,EPC,FCC,FCS,FDG,FGL,FMC,GQN,GTN,HAD,HAF,HAG,HAT,HAV,HBH,HDS,HGA,HHC,HKB,HKT,HLB,HNF,HNG,HNM,HNR,HSL,HVA,HVG,ICF,IDI,IDP,IFC,IFS,ILA,JOS,KDC,KHS,KSE,KTS,LAF,LSS,LYF,MCF,MCH,MCM,MLS,MML,MPC,MSN,NAF,NCS,NDF,NGC,NNQ,NSC,NSS,PAN,PCF,PRO,PRT,PSL,QHW,QNS,SAB,SAF,SB1,SBL,SBT,SCD,SCV,SEA,SGC,SGO,SJ1,SKH,SKN,SKV,SLS,SMB,SNC,SPD,SPH,SPV,SSC,SSN,SST,STD,STN,TAC,TAN,TAR,TCJ,TFC,THB,THP,TS4,VCF,VDL,VHC,VHF,VHI,VKD,VLC,VLF,VNH,VNM,VOC,VSF,VSN,VTL,WSB');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597380426515, 1597380426515, 14, 'Phương tiện truyền thông', 'Media', 'ADC,ADG,ALT,BDB,BED,BST,CAB,DAD,DAE,DNB,DST,EBS,ECI,EID,EPH,FHS,FOC,HAB,HBE,HEV,HTP,IBD,IBN,IHK,IKH,IN4,IN7,IPH,KBE,LBE,NBE,PNC,QST,RGC,SAP,SED,SGD,SMN,STC,STH,SUM,TPH,VEF,VNB,VNX,VPR,YEG');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597379645818, 1597379645818, 3, 'Công nghệ Thông tin', 'Technology', 'CKV,CMG,CMT,CNX,ELC,FPT,HIG,HPT,ICT,ITD,KST,LTC,ONE,PMJ,PMT,POT,SAM,SBD,SGT,SMT,SRA,SRB,ST8,TST,UNI,VAT,VEC,VIE,VLA,VTC,VTE');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597379908482, 1597379908482, 9, 'Du lịch & Giải trí', 'Travel & Leisure', 'ATS,BCV,BLN,BSG,BTV,CTC,CXH,DAH,DAR,DBH,DHQ,DLD,DLT,DNT,DSN,DSP,DTI,DXL,GTT,HES,HGT,HHG,HNT,HOT,HRT,HVN,KLF,KTC,MAS,MTC,NWT,OCH,ONW,PDC,PGT,RIC,SAS,SCS,SGH,SHX,SKG,SPS,SRT,STT,TCT,TPS,TR1,TSD,TSJ,TTT,VIR,VJC,VNG,VNS,VTD,VTG,VTM,VTR');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597380600572, 1597380600572, 19, 'Y tế', 'Health Care', 'AGP,AMP,AMV,APC,BCP,BIO,CBV,CDP,CNC,DAN,DBD,DBM,DBT,DCL,DDN,DHD,DHG,DHN,DHT,DKP,DMC,DMH,DNM,DP1,DP2,DP3,DPH,DPP,DTG,DTP,DVN,HDP,IMP,JVC,LDP,MED,MEF,MKP,MKV,MRF,MTP,NDC,NDP,NTF,OPC,PBC,PMC,PME,PPP,SJF,SPM,TNH,TRA,TTD,TVP,TW3,UPH,VDP,VHE,VMD,YTC');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597380564030, 1597380564030, 18, 'Xây dựng & Vật liệu', 'Construction & Materials', 'ACC,ACE,ACG,ACS,ADP,AMS,ATB,B82,BAX,BCC,BCE,BCO,BDT,BGT,BHC,BHT,BMN,BMP,BOT,BRM,BT6,BTD,BTN,BTS,BTU,BUD,C12,C32,C36,C47,C4G,C69,C71,C92,CC1,CC4,CCH,CCM,CCV,CDC,CDG,CDO,CDR,CDV,CE1,CEE,CEG,CGV,CH5,CHC,CI5,CID,CIG,CII,CIP,CKG,CLH,CMD,CNN,CNT,CPW,CQT,CRC,CT3,CT5,CT6,CTA,CTD,CTI,CTN,CTR,CTX,CVN,CVT,CX8,CYC,DAC,DC1,DC2,DC4,DCF,DCR,DCT,DGT,DHA,DIC,DID,DIH,DND,DNP,DPG,DSG,DTC,DTD,DTJ,DTK,DVG,DVW,DX2,DXD,DXV,E12,E29,EIC,EVG,FCM,FCN,FIC,G36,GAB,GH3,GKM,GMX,GND,GTH,GTS,H11,HAM,HAN,HAS,HBC,HC1,HC3,HCC,HCI,HDA,HEJ,HFB,HGC,HHV,HID,HLE,HLY,HMS,HNC,HOM,HPP,HSP,HT1,HT9,HTI,HU1,HU3,HU4,HUB,HUT,HVH,HVX,HWI,I10,ICC,ICG,ICI,ICN,ICS,INC,KCE,KDM,KHL,KPF,KSK,KTT,L12,L14,L18,L40,L45,L63,LAI,LBM,LCC,LCD,LCG,LCS,LDU,LG9,LHC,LIC,LIG,LM3,LM8,LUT,MBG,MCC,MCG,MCI,MCO,MCT,MDG,MEC,MES,MST,MT9,MVC,NAC,NAV,NDX,NED,NHA,NHC,NMK,NNC,NTP,NXT,PBT,PC1,PCC,PCM,PDB,PEN,PHC,PHH,PID,PLE,PNT,PSB,PSG,PTB,PTC,PTD,PTE,PTO,PVA,PVH,PVV,PVX,PVY,PX1,PXI,PXK,PXM,PXS,PXT,QCC,QLD,QNC,QNT,QTC,RCC,RCD,REN,ROS,S12,S27,S55,S72,S74,S96,S99,SAV,SBM,SC5,SCC,SCG,SCI,SCJ,SCL,SD1,SD2,SD3,SD4,SD5,SD6,SD7,SD8,SD9,SDB,SDD,SDH,SDJ,SDN,SDP,SDT,SDU,SDX,SDY,SGV,SHG,SHN,SIC,SIG,SII,SJC,SJE,SJG,SJM,SNZ,SVN,TA3,TA6,TA9,TBT,TBX,TCD,TCK,TCR,TDC,TDF,TDI,TEC,TEL,TGG,THG,THO,TKC,TL4,TLT,TMX,TNM,TRT,TS3,TS5,TTA,TTB,TTC,TTL,TTZ,TV3,TVA,TVG,TVH,TXM,UDC,UDJ,UIC,UMC,USC,V12,V15,V21,V45,VC1,VC2,VC5,VC6,VC7,VC9,VCC,VCE,VCG,VCP,VCS,VCX,VE1,VE2,VE3,VE4,VE8,VE9,VGC,VHH,VHL,VIH,VIT,VLB,VMC,VMI,VNE,VPC,VSI,VTA,VTS,VTV,VVN,VW1,VW3,VXB,X77,XLV,XMC,XMD,XVC,YBC');
INSERT INTO public."Industry"
("createdAt", "updatedAt", id, "industryName", "industryNameEn", "codeList")
VALUES(1597379941476, 1597379941476, 10, 'Hàng hóa & dịch vụ công nghiệp', 'Industrial Goods & Services', 'ABR,ACV,AGE,AME,APH,APL,ARM,ASG,AST,BAL,BBH,BBS,BLU,BMD,BPC,BRS,BTG,BTH,BTR,BXH,BXT,CAG,CAM,CAV,CCP,CCR,CCT,CDH,CDN,CFM,CIA,CJC,CKA,CKD,CKM,CLL,CMK,CMP,CMS,CPI,CQN,CTB,CTT,DAP,DAS,DDH,DDM,DFF,DHP,DKH,DL1,DNE,DNL,DNR,DOP,DPC,DS3,DSV,DT4,DTB,DUS,DVC,DVP,DXP,DZM,EMC,EME,EMG,EMS,ESL,FBC,FSO,FT1,GEX,GIC,GMA,GMD,GSP,HAH,HAW,HBD,HCT,HDO,HEC,HEM,HEP,HGR,HHN,HHR,HKP,HLR,HLS,HMH,HNB,HPB,HSA,HTH,HTK,HTR,HTU,HTV,ILB,ILC,ILS,IME,IMI,INN,IPA,ISG,IST,ITS,KIP,KTU,L10,L35,L43,L44,L61,L62,LGC,LLM,LM7,LMI,LO5,LPT,LQN,MA1,MAC,MBN,MCP,MDA,MDT,MHC,MHP,MHY,MIE,MLC,MND,MPY,MQB,MQN,MTB,MTH,MTL,MTS,MTV,MVN,MVY,NAG,NAP,NAS,NAU,NBR,NCT,NHP,NOS,NTR,NUE,PAC,PBP,PCT,PDN,PDV,PEC,PHN,PHP,PJC,PJT,PKR,PLO,PMP,PMS,PNP,PPE,PPS,PQN,PRC,PSC,PSN,PSP,PTS,PTT,PTX,PVM,PVP,PVT,PYU,QBR,QHD,QLT,QNU,QSP,RAT,REC,REE,RHN,RTH,RTS,SAC,SAL,SCO,SCY,SDA,SDC,SDG,SDK,SDV,SFI,SFN,SGN,SGP,SGS,SHC,SMA,SON,SPA,SPP,SRF,SSG,SSU,STG,STP,STS,STU,SVG,SVI,SVL,SWC,SZE,TAP,TB8,TBD,TCL,TCO,TCW,TDP,TGP,THI,THR,THU,TIE,TJC,TKA,TMS,TNP,TOT,TPP,TRS,TSB,TSG,TTP,TTU,TUG,TV1,TV2,TV4,TVM,TVU,TYA,UCT,UDL,UEM,USD,UTT,VBC,VBH,VCM,VCT,VEA,VES,VFC,VFR,VGP,VGR,VHG,VIN,VIP,VLG,VLP,VMS,VMT,VNA,VNC,VNF,VNL,VNT,VOS,VPA,VQC,VSA,VSC,VSE,VSG,VSM,VSP,VST,VTB,VTH,VTK,VTO,VTP,VTX,VXT,WCS,WTC,YRC');
