version: "3.2"
services:
  ftpserver:
    image: $REGISTRY:5000/tools/alpine-ftp-server
    volumes:
      - ftpserver_volume:/ftp/ftpuserreport/
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=ftpuserreport|ftpuserreport
      - ADDRESS=${HOST_MACHINE_FTP}
volumes:
  ftpserver_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$DATA_DIR/ftpserver'
